#!/usr/bin/env bash
# =============================================================================
# assemble_supplementary.sh
#
# Regenerates all BioTrajX fixture plots and assembles them into
# 11 manuscript-ready supplementary figure PDFs (S1-S11).
#
# Usage (from manuscript/ directory):
#   bash assemble_supplementary.sh
#
# Requirements:
#   R packages : see renv.lock + manuscript/scripts/setup/install_deps.R
#   Python pkgs: see environment.yml at the repo root (conda env "biotrajx_ti")
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANUSCRIPT_DIR="$(dirname "$SCRIPT_DIR")"
GIT_ROOT="$(dirname "$MANUSCRIPT_DIR")"
PLOTS_DIR="$SCRIPT_DIR/plots"
SUPP_DIR="$MANUSCRIPT_DIR/figures/supplementary"

cd "$SCRIPT_DIR"

# ── 1. Clean previous results ─────────────────────────────────────────────────
echo "Cleaning $PLOTS_DIR ..."
mkdir -p "$PLOTS_DIR"
find "$PLOTS_DIR" -type f \( -name "*.png" -o -name "*.csv" -o -name "*.pdf" \) -delete
echo "Done — $(ls "$PLOTS_DIR" | wc -l | tr -d ' ') files remaining."

# ── 2. Regenerate fixture plots ───────────────────────────────────────────────
echo ""
echo "Running visualize_fixtures.R ..."
cd "$GIT_ROOT"
Rscript manuscript/scripts/synthetic/visualize_fixtures.R "$PLOTS_DIR"
cd "$SCRIPT_DIR"
echo "Generated $(ls "$PLOTS_DIR"/*.pdf 2>/dev/null | wc -l | tr -d ' ') PDFs."


# ── 3. Assemble supplementary figures ─────────────────────────────────────────
echo ""
echo "Assembling supplementary figures ..."

# All figures below use true A4 (794x1123 px, the assemble_figure.py default).
# S1 and S11 need explicit per-row heights (in s1_layout.json / s11_layout.json)
# to fit without overflow; everything else fits at true A4 with its normal --cols.

# S2 — UMAPs for all synthetic fixtures (4 cols)
python3 assemble_figure.py \
  plots/[0-9][0-9]*_a_umap.pdf \
  --cols 4 \
  --figure-title "Figure S2. UMAP embeddings of synthetic trajectory fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS2.pdf

# S1 — metric summary heatmap (panel A: linear/endpoint; panel B: branched per-branch)
#       Row heights hand-tuned in s1_layout.json to fit true A4.
python3 assemble_figure.py \
  --layout s1_layout.json \
  --no-titles \
  --figure-title "Figure S1. Summary heatmap of DOE scores across synthetic fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS1.pdf


# S3 — Gene expression trends (linear: 9 panels; branched AB-only: 6 → 15 total, 3 cols)
python3 assemble_figure.py \
  plots/[0-9][0-9]*_b_gene_trends.pdf \
  plots/[0-9][0-9]*_b_gene_trends_AB.pdf \
  --cols 3 \
  --figure-title "Figure S3. Gene expression patterns across synthetic fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS3.pdf

# S4 — D metric (linear: 9 panels; branched AB-only: 6 → 15 total, 4 cols)
python3 assemble_figure.py \
  plots/[0-9][0-9]*_c_D_metric.pdf \
  plots/[0-9][0-9]*_c_D_metric_AB.pdf \
  --cols 4 \
  --figure-title "Figure S4. Directionality (D) metric evaluation across synthetic fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS4.pdf

# S5 — O metric (linear: 9 panels; branched AB-only: 6 → 15 total, 4 cols)
python3 assemble_figure.py \
  plots/[0-9][0-9]*_d_O_metric.pdf \
  plots/[0-9][0-9]*_d_O_metric_AB.pdf \
  --cols 4 \
  --figure-title "Figure S5. Ordering consistency (O) evaluation across synthetic fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS5.pdf

# S6 — E metric (linear: 9 panels; branched AB-only: 6 → 15 total, 4 cols)
python3 assemble_figure.py \
  plots/[0-9][0-9]*_e_E_metric.pdf \
  plots/[0-9][0-9]*_e_E_metric_AB.pdf \
  --cols 4 \
  --figure-title "Figure S6. Endpoint validity (E) evaluation across synthetic fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS6.pdf

# S7 — Ground-truth recovery (linear: 2 panels; branched stepwise AB-only: 2 → 4 total, 2 cols)
python3 assemble_figure.py \
  plots/[0-9][0-9]*_f_ground_truth.pdf \
  plots/[0-9][0-9]*_f_ground_truth_AB.pdf \
  --cols 2 \
  --figure-title "Figure S7. Ground-truth endpoint recovery across stepwise and branched stepwise fixtures" \
  --out-dir "$SUPP_DIR" \
  --out FigureS7.pdf

# S8 — GSE131847 LCMV time course, ground-truth day recovery (real data)
# Panels generated by: Rscript manuscript/scripts/real/make_figure_S8.R
#   A: UMAP grid | B+C: module trends + DOE heatmap | D+E: day-corr-vs-DOE + pseudotime-vs-day
python3 assemble_figure.py \
  --layout s8_layout.json \
  --no-titles \
  --figure-title "Figure S8. BioTrajX DOE score tracks ground-truth recovery of infection timing (GSE131847)" \
  --out-dir "$SUPP_DIR" \
  --out FigureS8.pdf

# S9 — CD8+ T cell exhaustion, linear trajectory (real data)
# Panels generated by: Rscript manuscript/scripts/real/make_figure_S9.R
#   A+B: UMAP grid + module trends | C+D: DOE heatmap + GAM TF trends | E: violin by cell type
python3 assemble_figure.py \
  --layout s9_layout.json \
  --no-titles \
  --figure-title "Figure S9. BioTrajX DOE evaluation on CD8+ T cell exhaustion (linear trajectory)" \
  --out-dir "$SUPP_DIR" \
  --out FigureS9.pdf

# S10 — Stem cell differentiation, branched trajectory (real data)
# Panels generated by: Rscript manuscript/scripts/real/make_figure_S10.R
# Split across two A4 pages (8 panels didn't fit legibly on one):
#   Page 1 (A-D): UMAP grid + DOE heatmap | branch UMAP | module trends
#   Page 2 (E-H): GAM TF trends per branch | violin by cell type per branch
python3 assemble_figure.py \
  --layout s10_page1_layout.json \
  --no-titles \
  --figure-title "Figure S10. BioTrajX DOE evaluation on stem cell differentiation (branched trajectory)" \
  --out-dir "$SUPP_DIR" \
  --out FigureS10.pdf

python3 assemble_figure.py \
  --layout s10_page2_layout.json \
  --no-titles \
  --figure-title "Figure S10 (continued). BioTrajX DOE evaluation on stem cell differentiation (branched trajectory)" \
  --out-dir "$SUPP_DIR" \
  --out FigureS10_cont.pdf

# S11 — Monocle3 root selection (real data)
# Panels generated by: Rscript manuscript/scripts/real/make_figure_S11.R
# Panel A spans full width (row 1); panels B-E in 2-column rows below.
# Row heights hand-tuned in s11_layout.json to fit true A4.
python3 assemble_figure.py \
  --layout s11_layout.json \
  --no-titles \
  --figure-title "Figure S11. BioTrajX DOE-guided root selection with Monocle3 on CD8+ T cells" \
  --out-dir "$SUPP_DIR" \
  --out FigureS11.pdf

echo ""
echo "All done. Output files:"
ls -lh "$SUPP_DIR"/pdf/FigureS*.pdf
